### ISSUE TITLE
Realworld example using try-block :+1: 

### ISSUE THREAD

**Issue by Shinigami92** [nzakas/proposal-write-once-const#2]
https://github.com/vitejs/vite/blob/69773520f214027070b0ff1a3344394f37ef19f8/packages/vite/src/node/optimizer/index.ts#L355-L377

<img src="https://github.com/nzakas/proposal-write-once-const/assets/7195563/3da019d4-f986-4588-9454-ec52287d05a6" width="500px" />

---

https://github.com/vitejs/vite/blob/69773520f214027070b0ff1a3344394f37ef19f8/packages/create-vite/src/index.ts#L258C7-L366

---

https://github.com/salsita/node-pg-migrate/blob/fde10af20cdaf822fc9de49c71c9124f09fd6b71/bin/node-pg-migrate.ts#L253-L282

<img src="https://github.com/nzakas/proposal-write-once-const/assets/7195563/976775cf-f771-44e7-a9c9-002296250dc1" width="500px" />

_not really as in line 263 there is a reassign, but nearly / or can be rewritten_

**Comment by nzakas** [comment]
Thank you! :pray:

**Comment by Shinigami92** [comment]
Some more examples (not try-catch)

https://github.com/faker-js/faker/blob/16ba43a6a4d1c93ac588c6b4c20b8c2a40213bdb/src/modules/date/index.ts#L623C9-L633 (`type`)

https://github.com/faker-js/faker/blob/16ba43a6a4d1c93ac588c6b4c20b8c2a40213bdb/src/modules/date/index.ts#L675-L685 (`type`)

https://github.com/faker-js/faker/blob/16ba43a6a4d1c93ac588c6b4c20b8c2a40213bdb/src/modules/helpers/eval.ts#L82C9-L89 (`index`)

https://github.com/faker-js/faker/blob/16ba43a6a4d1c93ac588c6b4c20b8c2a40213bdb/src/modules/system/index.ts#L265C9-L295 (`suffix`)

**Comment by nzakas** [comment]
Thanks!
