### ISSUE TITLE
Remove TDZ?

### ISSUE THREAD

**Issue by getify** [nzakas/proposal-write-once-const#3]
According to my research (asking those involved in ES6 spec writing, reading meeting notes, etc), the whole concept of TDZ was introduced to JS because of the "mutable const" problem.

Read here: https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/scope-closures/apA.md#whats-the-deal-with-tdz ("What's the Deal with TDZ?")

Summary: let and const have to "hoist" to top of their scope (otherwise quite surprising multiple duplicate bindings observable in a single scope). Since they have to hoist, const could be observed as having two values (undefined and its the eventually set value) and that's unacceptable semantics (surprising!). Thus, TDZ was born to prevent observation of const dual values. And then TDZ was added to "let" for consistency with "const".

----

So... here's my question. If this proposal is adopted, it would mean that TC39 has gone back on this "dual value const is unacceptable semantics" position it originally had. If they do reverse this position, it follows that the main (indeed, almost only) reason for TDZ to exist, will have been undone.

Doesn't it make sense to strengthen this proposal's coherency with the position that it implies that TDZ should also be removed?

Put another way, if this proposal is adopted, but TDZ is left in place, TDZ no longer has any relevant justification. Therefore, its fate is necessarily linked to the fate of "write once const".

**Comment by ljharb** [comment]
Given that there's a current proposal to remove TDZ entirely for performance reasons, I'm not sure there's much of a conflict here, but it's certainly related.

**Comment by karlhorky** [comment]
> there's a current proposal to remove TDZ entirely for performance reasons

Oh interesting, I didn't see that one yet, do you have a link?

Didn't find anything in [a search of `tc39/proposals`](https://github.com/search?q=repo%3Atc39%2Fproposals%20temporal%20dead%20zone&type=code), in `tc39/notes` found [some mention of TDZ and perf from 2012](https://github.com/tc39/notes/blob/57e6c4ef05d868129733ce31f200d68c688c8e33/meetings/2012-09/sept-19.md?plain=1#L599)

**Comment by getify** [comment]
@ljharb 

does the proposal for removing TDZ already imply the same outcome as *this* proposal?

or is there some way that "write only once const" could survive without TDZ?

**Comment by ljharb** [comment]
https://docs.google.com/presentation/d/1c-rhSUTQVNWD4DWgkNiC9tt50BruWDi7yRPllPHnff8/edit#slide=id.gc6f90357f_0_0 are the slides from the last presentation.

@getify no, i don't think they're really related. With or without TDZ, `const` can't currently be declared without a value, and with this proposal it would be declarable without a value and assignable once.

**Comment by nzakas** [comment]
As I stated in [this FAQ](https://github.com/nzakas/proposal-write-once-const?tab=readme-ov-file#why-throw-an-error-when-the-uninitialized-binding-is-read), I don't think TDZ vs. not is at all important to this proposal. I don't even personally care one way or another.

If I'm able to get this reviewed, my expectation is that TC39 would tell me what the correct approach is based on their current plans and proposals. I'm happy to go in either direction.
